Feature/settings-page-stripe-intergration
cascarita-io/cascarita pull request #126
Opened 2024-10-09 23:15 UTC by jipatino98

### Description

This PR adds the Stripe functionality to the Settings page so that users are able to connect their Stripe accounts using existing API routes. 

### Issue Link

N/A

### Checklist

- [x] I have tested the changes locally by running `npm run test`
- [x] I have added or updated relevant documentation
- [x] I have autoformatted the code by running `npm run eslint`
- [x] I have added test cases (if applicable)

### Additional Notes

2024-10-11 19:05 UTC, elimanzo requested changes
Hey @jipatino98 I mentioned some nits, but overall looks really good!

2024-10-11 19:05 UTC, elimanzo commented on client/pages/Settings/hooks.tsx
> +    queryKey: ["stripe_account", groupId ? groupId : 0],
I was always wondering is defaulting to 0 safe here?

2024-10-11 19:05 UTC, elimanzo commented on server/controllers/account.controller.js
> +        return_url: "http://localhost:3000/settings/payment",
is there a way we can get to `/settings/payment`. without needing `http://localhost:3000/`

2025-03-22 16:43 UTC, garcialuis commented
@jipatino98 This work has been completed in a separate PR, right? Can we close this one out?

2025-03-22 16:48 UTC, jipatino98 commented
@garcialuis yes we have! Go ahead and close that one

2025-03-22 16:53 UTC, closed without merging